version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_quaestum
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adonis_app
      MYSQL_USER: adonis
      MYSQL_PASSWORD: adonis
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
